/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
/*
import diptrace.DiptraceProject;
import diptrace.tokenizer.DiptraceToken;
import diptrace.tokenizer.DiptraceTokenizer;
import diptrace.tree.DiptraceItem;
*/
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author daniel
 */
public class JFrame_MainWindow extends javax.swing.JFrame {
	
//	DiptraceProject diptraceProject = new DiptraceProject();
	DefaultMutableTreeNode treeRootNode = new DefaultMutableTreeNode();
	DefaultTreeModel diptraceItemsTreeModel = new DefaultTreeModel(treeRootNode);
	
	
	/**
	 * Creates new form JFrame_MainWindow
	 */
	public JFrame_MainWindow() {
		initComponents();
	}
/*	
	public JFrame_MainWindow init() {
		readFile("F:\\Projekt\\americaN\\Corleone\\Corleone ställverk bas 1.1.asc");
//		readFile("F:\\Projekt\\americaN\\Corleone\\Corleone test.asc");
//		readFile("F:\\Projekt\\americaN\\Corleone\\empty.asc");
		
		fillTree(treeRootNode, diptraceProject.root);
//		jTree_DiptraceItems.collapsePath(path);
		jTree_DiptraceItems.expandRow(0);
		jTree_DiptraceItems.setRootVisible(false);
		
//		TreeModel model = jTree_DiptraceItems.getModel();
		
		return this;
	}
	
	private void fillTree(DefaultMutableTreeNode treeNode, DiptraceItem item) {
		for (DiptraceItem subItem : item.subItems) {
//			DefaultMutableTreeNode node = new DefaultMutableTreeNode(subItem.identifier);
			DefaultMutableTreeNode node = new DefaultMutableTreeNode(subItem.toString());
			treeNode.add(node);
			fillTree(node, subItem);
		}
	}
	
	private void readFile(String filename) {
		
		try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
			
			DiptraceTokenizer tokenizer = new DiptraceTokenizer(br);
			
			diptraceProject.parse(tokenizer);
/*			
			DiptraceToken token;
			while ((token = tokenizer.nextToken()) != null) {
//				System.out.format("Token: %s: %s\n", token.type.name(), token.getValue());
				System.err.format("Token: %s: %s\n", token.type.name(), token.getValue());
			}
*/			
/*			
			String line;
			
			int lineNo = 0;
			while ((line = br.readLine()) != null) {
				System.out.format("%d: %s\n", ++lineNo, line);
				jTextArea_Output.append(line);
			}
*./			
		} catch (FileNotFoundException ex) {
			Logger.getLogger(JFrame_MainWindow.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(JFrame_MainWindow.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
*/
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_DiptraceItems = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree_DiptraceItems.setModel(diptraceItemsTreeModel);
        jScrollPane1.setViewportView(jTree_DiptraceItems);

        jTextArea_Output.setColumns(20);
        jTextArea_Output.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_Output;
    private javax.swing.JTree jTree_DiptraceItems;
    // End of variables declaration//GEN-END:variables
}
